# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84422a09b0df394ae87ca1ffd89d0b8f2eba6878e5d566bf8fcbe86789832252fac9560d04a149730245fd9f2649f8a0fa686fc4f0b0891c6297b12adf9c9b69

test:
  secret_key_base: 4cffe6b2f7cb489aabf60434b53c513fbdbd9361a1fb4b90110d8192958079bbe8d5d69d0116470d7d0f3f21738fa73c1f605e0aac896184638bec6a7a66d0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
